import { Button } from "@/components/ui/button"
import { ExternalLink } from "lucide-react"

export default function NftHallContent() {
  return (
    <div className="flex flex-col items-center justify-center space-y-6 py-6">
      {/* Заголовок PIGGY DEFAI */}
      <h1 className="text-2xl font-extrabold text-center text-[#ff1493] tracking-wider">PIGGY DEFAI</h1>

      {/* Подзаголовок */}
      <p className="text-center text-white text-sm whitespace-nowrap">V1.0 AGENT NOW AVAILABLE ON TELEGRAM</p>

      {/* Кнопка USE THE PIGGY DEFAI BOT */}
      <a href="https://t.me/PiggyAgent_Bot" target="_blank" rel="noopener noreferrer" className="w-full max-w-xs">
        <Button size="lg" className="bg-[#ff1493] hover:bg-[#ff1493]/80 text-white font-bold w-full">
          USE THE PIGGY DEFAI BOT
          <ExternalLink className="ml-2 h-4 w-4" />
        </Button>
      </a>

      {/* Описание */}
      <p className="text-center text-white text-sm px-4 mt-2">
        Meet Piggy — your AI-powered, Telegram-based financial agent that grades your portfolio, optimizes your yield,
        and will even execute transactions so you can maximize earnings with zero hassle
      </p>

      {/* Блоки текста - уменьшенный размер */}
      <div className="space-y-4 mt-3">
        <p className="text-center text-white text-xs font-bold px-4">
          PIGGY UTILIZES SUPERFORM'S AGENT-OPTIMIZED V2 PROTOCOL TO ANALYZE EVERY ASSET ON EVERY CHAIN & ALL THE YIELD
          BEING GENERATED BY THESE ASSETS
        </p>

        <p className="text-center text-white text-xs font-bold px-4">THE FUTURE OF AI & CRYPTO LIVES WITH SUPERFORM</p>

        <p className="text-center text-white text-xs font-bold px-4">THE FUTURE OF AI & CRYPTO LIVES WITH PIGGY</p>
      </div>

      {/* Кнопка OINK IT */}
      <a
        href="https://mirror.xyz/basedpiggy.eth/SnvKX-LTceDZaEXO_-LWYCodGK68ftUIdSnnzy5B2HU"
        target="_blank"
        rel="noopener noreferrer"
        className="w-full max-w-xs mt-2"
      >
        <Button size="lg" className="bg-[#ff1493] hover:bg-[#ff1493]/80 text-white font-bold w-full">
          OINK IT
          <ExternalLink className="ml-2 h-4 w-4" />
        </Button>
      </a>

      {/* Кнопка Token Information */}
      <a href="https://piggy.vision" target="_blank" rel="noopener noreferrer" className="w-full max-w-xs">
        <Button
          variant="outline"
          size="lg"
          className="border-[#ff1493] text-[#ff1493] hover:bg-[#ff1493]/10 font-bold w-full"
        >
          Token Information
          <ExternalLink className="ml-2 h-4 w-4" />
        </Button>
      </a>
    </div>
  )
}
